#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#~ cp -ar constant/* constantBAC

cleanCase
rm -rf 0
rm -rf __pycache__
rm -f *.obj dodecagonal_contraction_sedimentation.foam
