#!/bin/sh
cd "${0%/*}" || exit 1

. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

rm -rf 0
mkdir 0
cp -r 0.org/. 0/

runApplication blockMesh
runApplication potentialFoam -initialiseUBCs -noFunctionObjects

application=$(getApplication)
runApplication "$application"
